# Generated by Django 3.1.5 on 2021-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproduct',
            name='about_discription',
            field=models.TextField(null=True),
        ),
    ]
