# Generated by Django 3.1.5 on 2021-01-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210109_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproduct',
            name='discription',
        ),
    ]
